/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import konfigurasi.DBKoneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer PC
 */
public class FrmLapMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form FrmLapMahasiswa
     */
    public FrmLapMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textfield_nim = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cetakJasper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textfield_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_nimActionPerformed(evt);
            }
        });

        jButton2.setText(" Cetak Semua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cetakJasper.setText("Cetak Jasper");
        cetakJasper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakJasperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textfield_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cetakJasper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(textfield_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cetakJasper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_nimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con=new DBKoneksi().connect();
        File file=new File("src/Laporan/ReportDataMahasiswa.jrxml");
        try {
            JasperDesign jd=JRXmlLoader.load(file);
            JRDesignQuery nq=new JRDesignQuery();
            String sql="select * from mahasiswa where nim="+textfield_nim.getText();
            nq.setText(sql);
            jd.setQuery(nq);
            JasperReport js=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(js,null,con);
            JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(FrmLapMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        Connection con=new DBKoneksi().connect();
        File file=new File("src/Laporan/ReportDataMahasiswa.jrxml");
        try {
            JasperDesign jd=JRXmlLoader.load(file);
            JRDesignQuery nq=new JRDesignQuery();
            String sql="select * from mahasiswa";
            nq.setText(sql);
            jd.setQuery(nq);
            JasperReport js=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(js,null,con);
           //cetak ke jasper viewer
            JasperViewer.viewReport(jp,false);
           //-----------------------------cetak ke pdf---------------------//
            //JasperExportManager.exportReportToPdfFile(jp, "sample.pdf")//
            //-----------------------------cetak ke pdf---------------------//
            
            
        } catch (JRException ex) {
            Logger.getLogger(FrmLapMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      //  JasperReport jasperReport = JasperCompileManager.compileReport("report.jrxml");
       // JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,new HashMap(), new JREmptyDataSource());
       // JasperExportManager.exportReportToPdfFile(jasperPrint, "sample.pdf");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection con=new DBKoneksi().connect();
        Statement st;
        ResultSet rs;
        try{  
                
                String namafile= "src/Laporan/ReportDataMahasiswa.jasper"; 
                String sql="select * from mahasiswa where nim=1209412";
                st=con.createStatement();
                rs=st.executeQuery(sql);
                HashMap param = new HashMap();                
                param.put("parameter1","tes"); 
                JRResultSetDataSource rsd=new JRResultSetDataSource(rs);
                System.out.println("tampilkan laporan");
                JasperPrint jp = JasperFillManager.fillReport(namafile,param,rsd);
                JasperViewer.viewReport(jp,false);
              } catch (SQLException e) {
              JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan" + e,"Cetak Laporan",JOptionPane.ERROR_MESSAGE);
              } catch (JRException ex) {
            Logger.getLogger(FrmLapMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cetakJasperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakJasperActionPerformed
        Connection con=new DBKoneksi().connect();
        String NamaFile = "./src/Laporan/reportMhs.jasper"; 
        HashMap param = new HashMap();                
        param.put("nim",Integer.parseInt(textfield_nim.getText())); 
        JasperPrint JPrint;            
        try 
        {
            JPrint = JasperFillManager.fillReport(NamaFile, param, con);
            JasperViewer.viewReport(JPrint);
        } catch (JRException ex) {
            Logger.getLogger(FrmLapMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_cetakJasperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLapMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetakJasper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField textfield_nim;
    // End of variables declaration//GEN-END:variables
}
